INSERT INTO TBL_PRODUCT (PRICE, PRODUCT_NAME) VALUES (10, 'Product 1');
INSERT INTO TBL_PRODUCT (PRICE, PRODUCT_NAME) VALUES (20, 'Product 2');
INSERT INTO TBL_PRODUCT (PRICE, PRODUCT_NAME) VALUES (30, 'Product 3');
INSERT INTO TBL_PRODUCT (PRICE, PRODUCT_NAME) VALUES (40, 'Maça');